[versions]
kotlin = "1.9.22"
ktor = "2.3.8"
kord = "1.7.1-SNAPSHOT"
ksp = "1.9.22-1.0.16"
scrimmage = "4.1.1"
kotlin-dl = "0.5.2"
komapper = "1.16.0"
ktlint-plugin = "12.0.3"

[libraries]
kord-ex = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord" }
kord-emoji = "dev.kord.x:emoji:0.5.0"

scrimmage-core = { module = "com.sksamuel.scrimage:scrimage-core", version.ref = "scrimmage" }
scrimmage-filters = { module = "com.sksamuel.scrimage:scrimage-filters", version.ref = "scrimmage" }
scrimmage-webp = { module = "com.sksamuel.scrimage:scrimage-webp", version.ref = "scrimmage" }

kotlin-dl-tensorflow = { module = "org.jetbrains.kotlinx:kotlin-deeplearning-tensorflow", version.ref = "kotlin-dl" }
kotlin-dl-onnx = { module = "org.jetbrains.kotlinx:kotlin-deeplearning-onnx", version.ref = "kotlin-dl" }
kotlin-dl-visualization = { module = "org.jetbrains.kotlinx:kotlin-deeplearning-visualization", version.ref = "kotlin-dl" }

komapper-starter-r2dbc = { module = "org.komapper:komapper-starter-r2dbc", version.ref = "komapper" }
komapper-dialect-h2-r2dbc = { module = "org.komapper:komapper-dialect-h2-r2dbc", version.ref = "komapper" }

komapper-processor = { module = "org.komapper:komapper-processor", version.ref = "komapper" }

ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }

logback-classic = "ch.qos.logback:logback-classic:1.4.14"
openai-client = "com.aallam.openai:openai-client:3.6.1"
tess4j = "net.sourceforge.tess4j:tess4j:5.8.0"

[bundles]
scrimmage = ["scrimmage-core", "scrimmage-filters", "scrimmage-webp"]
komapper = ["komapper-starter-r2dbc", "komapper-dialect-h2-r2dbc"]
kotlin-dl = ["kotlin-dl-tensorflow", "kotlin-dl-onnx", "kotlin-dl-visualization"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }