name: Build and push Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [{name: linux/amd64}, {name: linux/arm64, prefix: arm64/}]
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get repo name
      id: get-repo
      run: |
        echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

    - name: Apply platform-specific image prefix
      run: sed -i 's/FROM eclipse-temurin/FROM ${{ matrix.platform.prefix }}eclipse-temurin/g' ./dockerfile

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ steps.get-repo.outputs.repo }}:latest
        platforms: ${{ matrix.platform.name }}